# Generated by Django 2.0.4 on 2018-04-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20180416_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='ayes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='nays',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
